### PR TITLE
fix: metamask popup without doing any action

### LINKED ISSUE #78: perf: metamask request to sign into the app at the loading
### Acceptance criteria

- [ ] Metamask Pop up should appear only when the user click on SIWE button.

### PR DESCRIPTION
**Pull request by farrellh1**
# Description

fix metamask popup without doing any action

Fixes #78 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines

### CODE REVIEW

**Review by dasarathg68 — COMMENTED** [review]
https://github.com/globe-and-citizen/cnc-portal/issues/78 The acceptance criterion is that metamask request to connect the wallet should appear only when user click on SIWE button.
This definitely does solve the issue but I don't think it's the best way to do it.
I think it's part of a bigger problem where the NavBar is mounted in the login page even when it's not supposed to. If we solve that, I think this would also be rectified in the process.

**Comment by farrellh1** [comment]
> #78 The acceptance criterion is that metamask request to connect the wallet should appear only when user click on SIWE button. This definitely does solve the issue but I don't think it's the best way to do it. I think it's part of a bigger problem where the NavBar is mounted in the login page even when it's not supposed to. If we solve that, I think this would also be rectified in the process.

yes agree, and route.path somehow always show root path '/', i still haven't figure that out
image

image

**Comment by dasarathg68** [comment]
> > #78 The acceptance criterion is that metamask request to connect the wallet should appear only when user click on SIWE button. This definitely does solve the issue but I don't think it's the best way to do it. I think it's part of a bigger problem where the NavBar is mounted in the login page even when it's not supposed to. If we solve that, I think this would also be rectified in the process.
> 
> yes agree, and route.path somehow always show root path '/', i still haven't figure that out image
> 
> image

Yes I noticed it as well but when we print the route object the values look right as shown below
image

**Comment by farrellh1** [comment]
when u print entire `route` it will shows `/login` but when u print `route.path` it returns `/`. so it doesn't come into the condition if path is `/login`
image
image

**Review by hermannleboss — APPROVED** [review]
LGTM

**Comment by hermannleboss** [comment]
I fixed it. By checking if the user is auth before i mount the nav Bar

In the App.vue file, the route is / before it's change to /login
My fix is not using the route again to check if the nav should be mount or not

**Comment by farrellh1** [comment]
@hermannleboss i think u forgot to load the balance

**Pull request merged**
