### PR TITLE
refactor: bank

### PR DESCRIPTION
**Pull request by farrellh1**
# Description

Refactor bank feature

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines

### CODE REVIEW

**Comment by dasarathg68** [comment]
What do you think about following the same pattern? Governance/Voting in one, Team/Member in one folder and Banking components in a separate folder
image

**Review by dasarathg68 — COMMENTED** [review]
How did you fix the tests?

**Comment by hermannleboss** [comment]
> What do you think about following the same pattern? Governance/Voting in one, Team/Member in one folder and Banking components in a separate folde

I request him that he don't need to create a folder for everything. 
We have section in the page folder and all component are grouped to usage. : Form, Table, UI ...

**Comment by farrellh1** [comment]
> TeamAccount

i didn't fix it yet, will do it on another PR

**Pull request merged**
