### PR TITLE
Feat/improve status ux

### LINKED ISSUE #167: ux: Team status is not clear
## Description

The UX need to be update to help the user understand what is happening. 

The user should know the different when he don't have any team yet or if the backend do not respond yet. 

## Acceptance Criteria

- [ ] Loading when the team data is loading from the backend
- [ ] Empty team should be different to not loaded team
- [ ] Loading then taost when you opperate something: 
- [ ] ex: Add team member: loading then toast the result message
- [ ] TODO: Create, Update, Delete Team, Add team member, remove team member.

### PR DESCRIPTION
**Pull request by dasarathg68**
# Description

Refactors our existing API calls by moving them to composable functions. Additionally, it implements loading logic to provide a better UX during async.
Fixes #167 

## Type of change

Please delete options that are not relevant.
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)

### CODE REVIEW

**Review by hermannleboss — CHANGES_REQUESTED** [review]
I prefer if you use useFetch instead of building something who look like it.

**Comment by hermannleboss** [comment]
@dasarathg68 look in the UseCustome fecth composable and inside Team View how i do it. 
It's more simple to use it in this way. 

And here the documentation of useFetch

https://vueuse.org/core/useFetch/#usefetch

**Comment by dasarathg68** [comment]
@hermannleboss I have followed your recommendations and I'm done with the refactoring. Please check

**Review by hermannleboss — APPROVED** [review]
LGTM

**Comment by hermannleboss** [comment]
@dasarathg68 26 files in a PR is too much
Let's avoid this in the futre. 
You can split your PR in many small PR.

**Pull request merged**
