### PR TITLE
feat/ implement toggling between themes using vueuse

### LINKED ISSUE #97: bug: brokend darkmode
## Desctiption

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by dasarathg68**
# Description

Implements vueuse for toggling between themes

Fix #97 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines

### CODE REVIEW

**Comment by hermannleboss** [comment]
@dasarathg68 The dark mode is not specialy linked to vue use. 
VueUse is a way to handle dark mode. 
But by default Daisy Ui handle dark mode.

I will say 
- Fix dark mode with daysi UI 
- Toggle with vueUse

You can do it in the order you want

**Comment by dasarathg68** [comment]
> @dasarathg68 The dark mode is not specialy linked to vue use. VueUse is a way to handle dark mode. But by default Daisy Ui handle dark mode.
> 
> I will say
> 
> * Fix dark mode with daysi UI
> * Toggle with vueUse
> 
> You can do it in the order you want

Hey that's what I'm already doing.
VueUse utilities useDark, useToggle are used to persist changes across page reloads (internally it uses localStorage) and DaisyUI theme controller switches the theme reading the value from useDark() method.

**Comment by hermannleboss** [comment]
@dasarathg68 let's find a way to enforce light mode everytimes and when we find design for dark mode we will use it.

**Comment by dasarathg68** [comment]
> @dasarathg68 let's find a way to enforce light mode everytimes and when we find design for dark mode we will use it.

@hermannleboss please check now, i have implemented this.

**Pull request merged**
