### PR TITLE
Feature/deploy ad campaign contract

### PR DESCRIPTION
**Pull request by achillegley**
# Description
backend/src/controllers/teamController.ts
This change ensures that when a [teamContract] is provided, the contract address is validated. If the contract already exists in the database, it is updated with the new details. If it does not exist, a new entry is created.

app/src/services/AddCampaignService.ts
This update includes the implementation of the AdCampaignService class, which provides methods to manage ad campaigns. The class includes functionalities to create ad campaign managers, add admins, retrieve admin lists, get contract data, and fetch events grouped by campaign code. The implementation ensures proper handling of contract interactions and data retrieval.

app/src/services/__tests__/AddCampaignService.spec.ts
test file for the addCamapaignService. 

app/src/composables/addCampaign.ts
This update includes the implementation of the [useDeployAddCampaignContract] composable function, which provides a method to deploy an ad campaign contract. The function handles input validation, contract deployment, and state management for loading, success, and error states.

app/src/composables/__tests__/addCampaign.spec.ts
app/src/composables/addCampaign.ts

### CODE REVIEW

**Comment by hermannleboss** [comment]
@achillegley we are planing to remove ether js.
Can you check how we are doing it with wagmi and viem and refactor your code according to it ?

**Review by dasarathg68 — COMMENTED** [review]
https://github.com/globe-and-citizen/cnc-portal/issues/349
Use the PRs linked to this issue as a reference to how wagmi can be used instead of the current ethers implementation.

**Comment by achillegley** [comment]
@dasarathg68 @hermannleboss 
i get your point about the wagmi. 
1. i need to focus first on my local changes progressive PRS. 
2. If possible just do the merges on your local develop. then let me know if everything goes well. i will have progresive update then wait for your feedback. 
3. once we're good on 1 and 2 i will  reformat the ether js functions to Wagmi.

**Review by hermannleboss — APPROVED** [review]
LGTM

**Pull request merged**
