### PR TITLE
Feat/expense account bod implementation

### PR DESCRIPTION
**Pull request by aliassan**
# Description

Adds BoD implementation to the Expense Account section.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by hermannleboss** [comment]
Approve user is working. 
Now we need others functions.

**Review by dasarathg68 — COMMENTED** [review]
Disapprove and approve user not working after transferring ownership to BoD (it does not create an action)

**Comment by aliassan** [comment]
> Disapprove and approve user not working after transferring ownership to BoD (it does not create an action)

It's working on my side, are you using this branch not the board of directors tab one, this one doesn't have that functionality:

https://github.com/globe-and-citizen/cnc-portal/tree/feature/board-of-director-ali

**Review by hermannleboss — APPROVED** [review]
LGTM

**Review by hermannleboss — COMMENTED** [review]
I think at this point we can merge it. 
We will focus on the testing later.

**Comment by dasarathg68** [comment]
> > Disapprove and approve user not working after transferring ownership to BoD (it does not create an action)
> 
> It's working on my side, are you using this branch not the board of directors tab one, this one doesn't have that functionality:
> 
> https://github.com/globe-and-citizen/cnc-portal/tree/feature/board-of-director-ali

https://www.loom.com/share/224c11a0fe2b45ce907b0e964efb5836?sid=6e9909c7-0856-454a-a534-05894bdd263f

**Comment by hermannleboss** [comment]
Yes i remark this also. 

It's because there is no description. 

Add a description and it should work.

**Review by dasarathg68 — APPROVED** [review]
LGTM

**Pull request merged**
