### PR TITLE
chore: upgrade synpress

### PR DESCRIPTION
**Pull request by farrellh1**
# Description

Upgrade synpress to stable version

Fixes # (issue)

## Contribution

For your PR please add a commnent to eache file edited to explain the changes you made.

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

Make sur you run the following commands before submitting your PR:

- /app

```bash
npm run build
npm run test:unit
npm run type-check
npm run lint
npm run format
```

- /backend

```bash
npm run build
npm run test
npm run lint
npm run format
```

- /contract

```bash
npm run test
npm run lint
npm run format
```

- **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

### CODE REVIEW

**Comment by farrellh1** [comment]
will add documentation on README file

**Review by hermannleboss — COMMENTED** [review]
Look Good to me

**Comment by dasarathg68** [comment]
image

**Comment by dasarathg68** [comment]
> image

Fix: just update node version to the latest.

**Review by dasarathg68 — APPROVED** [review]
LGTM 🚀 

If possible, add a wiki for e2e and best practices since it's new for us.

**Pull request merged**
